[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300

[nixpacks]
features = ["nodejs"]

[nixpacks.env]
NODE_ENV = "production"
NODE_VERSION = "18"
NPM_FLAGS = "--legacy-peer-deps --no-optional"
PORT = "3000"
